services:
  users-pg-db:
    image: postgres:16
    container_name: nest-postgres-pg-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_POSTGRES_DB}
    volumes:
      - users-pg-db:/var/lib/postgresql/data
    networks:
      - aye-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - aye-network
    restart: unless-stopped

  users-microservice:
    build:
      context: ./users-microservice
      dockerfile: Dockerfile
    depends_on:
    - users-pg-db
    networks:
    - aye-network
    environment:
      USERS_POSTGRES_HOST: ${USERS_POSTGRES_HOST}
      USERS_POSTGRES_PORT: ${USERS_POSTGRES_PORT}
      USERS_POSTGRES_USER: ${USERS_POSTGRES_USER}
      USERS_POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      USERS_POSTGRES_DB: ${USERS_POSTGRES_DB}
      TYPEORM_CACHE_DURATION: ${TYPEORM_CACHE_DURATION}
    
  auth-microservice:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile
    depends_on:
      - users-pg-db
    networks:
      - aye-network
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - aye-network
    depends_on:
      - users-microservice
      - auth-microservice

networks:
  aye-network:
    driver: bridge

volumes:
  users-pg-db:
  pgadmin:
